### ISSUE TITLE
[Bug]: component has a white background

### ISSUE THREAD

**Issue by jaulz** [malzariey/filament-daterangepicker-filter#199]
### What happened?

If I move the date range picker next to the user menu the input has a white background:
<img width="488" height="56" alt="Image" src="https://github.com/user-attachments/assets/37ff6761-bc08-4d67-971f-a35e68f7a170" />

The reason is this line:
https://github.com/malzariey/filament-daterangepicker-filter/blob/da819c35b603f991697a3a84806bb76d954d6479/resources/views/date-range-picker.blade.php#L122

I removed those two classes and then it looked fine.

Is there any way to prevent this? What's the reason to put the classes there at all?

### How to reproduce the bug

In the PanelProvider:
```
Livewire::component('test', App\Livewire\Test::class);

...

->renderHook(PanelsRenderHook::USER_MENU_BEFORE, function () {
                return Blade::render("@livewire('test')");
            })
```

And then the Test component:
```php
<?php

namespace App\Livewire;

use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Schemas\Schema;
use Illuminate\View\ComponentAttributeBag;
use Livewire\Component;
use Malzariey\FilamentDaterangepickerFilter\Fields\DateRangePicker;

class Test extends Component implements HasForms
{
    use InteractsWithForms;

    public function mount(): void
    {
    }

    public function getExtraAttributeBag(): ComponentAttributeBag
    {
        return new ComponentAttributeBag;
    }

    public function form(Schema $schema): Schema
    {
        return $schema->components(
            [
                DateRangePicker::make('period')->label(__('Period'))->hiddenLabel(true)
                    ->autoApply()->live()
                    ->separator('-')
                    ->displayFormat('YYYY-MM-DD')
                    ->format('Y-m-d')
                    ->extraInputAttributes(['style' => 'width: 12.5rem;']),
            ],
        )->columns(2);
    }
}
```

### Package Version

4.0.6

### PHP Version

8.3.0

### Laravel Version

12.0.x

**Comment by quelo83** [comment]
The problem is that the class "dark:bg-white/5" does not exist in your css file.

Maybe it should be included in the filament-daterangepicker.css file, but as a workaround you can source the date range picker view into your theme.css file so Tailwind can detect and include it:

```
@source '../../../../vendor/malzariey/filament-daterangepicker-filter/resources/views/date-range-picker.blade.php';
```

**Comment by malzariey** [comment]
Thank you for raising the issue!

We are shifting focus to our new architecture in v4.1.beta (Build #211 ), which likely resolves the underlying problem this PR addresses.

Could you please test the new beta version? If the issue is already fixed there, we may close this Issue to keep the codebase clean. If the fix is still needed, please let us know how it applies to the new version.

**Comment by k3rielit** [comment]
This is still an issue in v4.0.8 (released on 2026.01.24.) if I just used it as a regular table filter with a custom filament theme. The solution is still the same, add this to the theme.css file:

```css
@source '../../../../vendor/malzariey/filament-daterangepicker-filter/resources/views/**/*.blade.php';
```

Now Tailwind can detect classes inside the vendor Blade files.

Adding this to the installation steps in the readme would probably help a lot of people. 

On a sidenote, the package description has a typo, " This package uses **daterangepciker** library".
